FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN set -eux; \
    apk add --no-cache libc6-compat; \
    npm config set cache /tmp/.npm; \
    npm ci; \
    rm -rf /tmp/.npm
COPY . .
RUN set -eux; \
    npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
EXPOSE 3000
CMD ["node", "server.js"]
